name: Deploy to Fly.io

# Ejecutar solo cuando haya un push a la rama 'main'
on:
  push:
    branches:
      - main  # Despliega solo cuando se haga merge a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        export FLYCTL_INSTALL="$HOME/.fly"
        export PATH="$FLYCTL_INSTALL/bin:$PATH"
        echo "$FLYCTL_INSTALL/bin" >> $GITHUB_PATH

    - name: Authenticate to Fly.io
      run: fly auth token ${{ secrets.FLY_API_TOKEN }}

    - name: Deploy to Fly.io
      run: fly deploy --remote-only
