name: Deploy to Fly.io

# Ejecutar solo cuando haya un push a la rama 'main'
on:
  push:
    branches:
      - main  # Despliega solo cuando se haga merge a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Fly.io CLI
      run: |
        curl -L https://fly.io/install.sh | sh
        export FLYCTL_INSTALL="$HOME/.fly"
        export PATH="$FLYCTL_INSTALL/bin:$PATH"
        echo "$FLYCTL_INSTALL/bin" >> $GITHUB_PATH  # Agregar al PATH global

    - name: Deploy to Fly.io
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}  # Usa el token de los secrets
      run: |
        flyctl auth token $FLY_API_TOKEN
        flyctl deploy --remote-only
